name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Linting and testing
        run: npm run lint && npm test

      - name: Build Docker image
        run: docker build -t my_first_image:dev .

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker push my_first_image:dev

      - name: Deploy to test environment
        run: |
          docker stop awesome_matsumoto || true
          docker rm awesome_matsumoto || true
          docker run -d --name awesome_matsumoto -p 3000:3000 my_first_image:dev
